name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 2. Build and Deploy
      uses: jinuxx/hexo-deploy-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_REPOSITORY: jinuxx/jinuxx.github.io
        BRANCH: gh-pages
        PUBLISH_DIR: ./public
        CNAME: acquiesce.highflyingbird.ink

